### ISSUE TITLE
"ArtifactWorld" scene missing ShakingMarker on Portal; Shaking is always active as a result

### ISSUE THREAD

**Issue by LordVGames** [DestroyedClone/LobbyAppearanceImprovements#12]
Before the mod's latest update, either the artifact place wasn't shaking because of the shaking setting or the shaking in the scene didn't work. Now it shakes a lot and it isn't toggled off with the shaking setting. I tried deleting the mod's config to see if that was the reason but it wasn't.

https://github.com/DestroyedClone/LobbyAppearanceImprovements/assets/51967559/9e44508e-d5c3-4298-8bb1-2e32189bda4f

**Comment by DestroyedClone** [comment]
In `CameraRigController.cs` it has a method for `SetCameraState` which has the following two lines:
```cs
float d = (this.localUserViewer == null) ? 1f : this.localUserViewer.userProfile.screenShakeScale;
this.rawScreenShakeDisplacement = ShakeEmitter.ComputeTotalShakeAtPoint(cameraState.position);
```
The game is ignoring the screen shake scale because the CameraRigController in the ror2 lobby doesn't have a localUserViewer. this is also probably why some character select displays shake the camera too

Only solution on my end is to either kill the shake emitters myself or have a secondary patch for it

**Comment by DestroyedClone** [comment]
Fixed with https://github.com/DestroyedClone/LobbyAppearanceImprovements/commit/3989b7a2529fa8f317a3c1434bff78734b77a90d
